export interface EvidenceChunk {
  id: string
  title: string
  publisher: string
  url: string
  published: string
  excerpt: string
  whyItMatters: string
  tags: string[]
  quantitative: boolean
}

export const EVIDENCE_CORPUS: EvidenceChunk[] = [
  {
    id: 'bls-software-outlook',
    title: 'Software Developers: Occupational Outlook',
    publisher: 'U.S. Bureau of Labor Statistics',
    url: 'https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm',
    published: '2025',
    excerpt: 'BLS reports a May 2024 median annual wage of $133,080 for software developers and projects 16% employment growth from 2024 to 2034.',
    whyItMatters: 'A stable software role has a meaningful, evidence-backed financial floor and durable labor demand.',
    tags: ['software', 'salary', 'employment', 'stability', 'career'],
    quantitative: true,
  },
  {
    id: 'bls-software-teamwork',
    title: 'Software Developer Work Environment',
    publisher: 'U.S. Bureau of Labor Statistics',
    url: 'https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm#tab-3',
    published: '2025',
    excerpt: 'BLS describes software development as a collaborative process and notes that developers commonly work in teams.',
    whyItMatters: 'Team structure can provide mentorship and career capital, but the actual role still needs to be verified.',
    tags: ['software', 'team', 'mentorship', 'career capital'],
    quantitative: false,
  },
  {
    id: 'bls-ai-demand',
    title: 'Software Employment Demand',
    publisher: 'U.S. Bureau of Labor Statistics',
    url: 'https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm#tab-6',
    published: '2025',
    excerpt: 'BLS links continued software demand partly to expansion in artificial intelligence, robotics, automation, and connected products.',
    whyItMatters: 'The job path can still compound AI-relevant career capital when the role offers genuine access to that work.',
    tags: ['AI', 'software', 'demand', 'career capital'],
    quantitative: false,
  },
  {
    id: 'sba-startup-survival',
    title: 'Frequently Asked Questions About Small Business',
    publisher: 'U.S. Small Business Administration Office of Advocacy',
    url: 'https://advocacy.sba.gov/wp-content/uploads/2023/03/Frequently-Asked-Questions-About-Small-Business-March-2023-508c.pdf',
    published: '2023',
    excerpt: 'Across 1994–2020 cohorts, SBA reports that 67.7% of new employer establishments survived two years and 48.9% survived five years.',
    whyItMatters: 'A startup path deserves a wider downside range. These establishment-level base rates are context, not a prediction for one company.',
    tags: ['startup', 'survival', 'base rate', 'risk', 'company'],
    quantitative: true,
  },
  {
    id: 'carta-equity-liquidity',
    title: 'Liquidity Events',
    publisher: 'Carta',
    url: 'https://carta.com/learn/equity/liquidity-events/',
    published: '2023',
    excerpt: 'Carta explains that private-company stock options are illiquid and may be difficult to convert to cash without an IPO, acquisition, or secondary transaction.',
    whyItMatters: 'Startup equity should not be scored as guaranteed cash compensation or a reliable financial floor.',
    tags: ['startup', 'equity', 'liquidity', 'options', 'cash', 'risk'],
    quantitative: false,
  },
  {
    id: 'carta-equity-exercise',
    title: 'Private Equity and Job Offers',
    publisher: 'Carta',
    url: 'https://carta.com/learn/equity/private-company-equity/',
    published: '2019',
    excerpt: 'Private-company option holders may need to pay an exercise cost and taxes before an uncertain future liquidity event.',
    whyItMatters: 'Headline grant value can overstate usable near-term compensation, especially for someone with limited savings.',
    tags: ['equity', 'exercise', 'tax', 'limited savings', 'compensation'],
    quantitative: false,
  },
  {
    id: 'nsf-graduate-support',
    title: 'Funding for Graduate Students',
    publisher: 'U.S. National Science Foundation',
    url: 'https://www.nsf.gov/funding/graduate-students',
    published: '2026',
    excerpt: 'NSF lists support for research-based STEM master’s and doctoral students through fellowships, project budgets, traineeships, stipends, and cost-of-education allowances.',
    whyItMatters: 'Verified funding can materially reduce the financial downside of a research path while preserving focused research time.',
    tags: ['graduate', 'research', 'masters', 'funding', 'stipend', 'tuition', 'AI'],
    quantitative: false,
  },
  {
    id: 'nsf-research-network',
    title: 'Graduate Research Opportunities',
    publisher: 'U.S. National Science Foundation',
    url: 'https://www.nsf.gov/funding/graduate-students',
    published: '2026',
    excerpt: 'NSF-supported research programs pair graduate training with mentoring, research projects, and professional-network development.',
    whyItMatters: 'Strong lab and advisor access can increase both technical depth and future research or industry options.',
    tags: ['research', 'mentorship', 'network', 'lab', 'career capital'],
    quantitative: false,
  },
  {
    id: 'education-opportunity-cost',
    title: 'How to Evaluate Financial Aid Offers',
    publisher: 'U.S. Department of Education, Federal Student Aid',
    url: 'https://studentaid.gov/articles/evaluating-financial-aid-offers/',
    published: '2026',
    excerpt: 'Federal Student Aid distinguishes grants, work-study, and loans, and notes that graduate students may use Direct PLUS loans for costs not covered by other aid.',
    whyItMatters: 'A program described as funded must be checked carefully: grants and stipends are not equivalent to debt or uncertain work-study income.',
    tags: ['graduate', 'funding', 'loans', 'work study', 'cost', 'financial aid'],
    quantitative: false,
  },
  {
    id: 'education-work-study',
    title: 'Federal Work-Study Facts',
    publisher: 'U.S. Department of Education, Federal Student Aid',
    url: 'https://studentaid.gov/articles/8-things-federal-work-study/',
    published: '2026',
    excerpt: 'Federal Work-Study positions are limited, generally part time, and require the student to secure and perform a job to receive earnings.',
    whyItMatters: 'Work-study should not be treated as guaranteed program funding when comparing financial floors.',
    tags: ['graduate', 'work study', 'funding', 'income', 'uncertainty'],
    quantitative: false,
  },
  {
    id: 'bls-software-full-time',
    title: 'Software Developer Work Schedules',
    publisher: 'U.S. Bureau of Labor Statistics',
    url: 'https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm#tab-3',
    published: '2025',
    excerpt: 'BLS reports that most software developers, quality assurance analysts, and testers work full time.',
    whyItMatters: 'A stable role can provide predictable full-time employment, but the specific workload and flexibility still require diligence.',
    tags: ['software', 'full time', 'schedule', 'stability', 'workload'],
    quantitative: false,
  },
  {
    id: 'bls-software-education',
    title: 'Software Developer Education',
    publisher: 'U.S. Bureau of Labor Statistics',
    url: 'https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm#tab-4',
    published: '2025',
    excerpt: 'Software developers typically need a bachelor’s degree, while some employers prefer candidates with a master’s degree.',
    whyItMatters: 'A graduate degree may help for some roles, but it is not a universal requirement for software employment.',
    tags: ['software', 'education', 'bachelors', 'masters', 'career'],
    quantitative: false,
  },
  {
    id: 'bls-software-continuous-learning',
    title: 'Keeping Software Skills Current',
    publisher: 'U.S. Bureau of Labor Statistics',
    url: 'https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm#tab-4',
    published: '2025',
    excerpt: 'BLS notes that software developers must keep up to date on new tools and computer languages throughout their careers.',
    whyItMatters: 'A stable job supports the AI goal only when the role leaves room for continued technical learning.',
    tags: ['software', 'learning', 'skills', 'AI growth', 'career capital'],
    quantitative: false,
  },
  {
    id: 'bls-software-advancement',
    title: 'Software Developer Advancement',
    publisher: 'U.S. Bureau of Labor Statistics',
    url: 'https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm#tab-4',
    published: '2025',
    excerpt: 'BLS describes advancement from software development into project management and computer and information systems management.',
    whyItMatters: 'A conventional role can create management and leadership options in addition to technical progression.',
    tags: ['software', 'advancement', 'management', 'leadership', 'optionality'],
    quantitative: false,
  },
  {
    id: 'bls-software-industries',
    title: 'Software Employment Across Industries',
    publisher: 'U.S. Bureau of Labor Statistics',
    url: 'https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm#tab-3',
    published: '2025',
    excerpt: 'Software developers work across systems design, finance and insurance, software publishing, manufacturing, and company management.',
    whyItMatters: 'Demand across several industries can preserve mobility if one employer or sector becomes a poor fit.',
    tags: ['software', 'industries', 'mobility', 'stability', 'optionality'],
    quantitative: false,
  },
  {
    id: 'bls-software-user-needs',
    title: 'Software Developer Responsibilities',
    publisher: 'U.S. Bureau of Labor Statistics',
    url: 'https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm#tab-2',
    published: '2025',
    excerpt: 'Developers analyze user needs, design systems, plan how components work together, test software, and maintain it after release.',
    whyItMatters: 'A stable role may build broad engineering judgment, although it does not guarantee deep AI research exposure.',
    tags: ['software', 'engineering', 'systems', 'learning', 'role quality'],
    quantitative: false,
  },
  {
    id: 'carta-equity-vesting',
    title: 'Employee Equity Vesting',
    publisher: 'Carta',
    url: 'https://carta.com/learn/equity/leaving-company/',
    published: '2023',
    excerpt: 'Employee equity is commonly earned over time through vesting, often with a one-year cliff before any options vest.',
    whyItMatters: 'A headline grant may provide no ownership if the employee leaves before the cliff.',
    tags: ['startup', 'equity', 'vesting', 'cliff', 'ownership', 'risk'],
    quantitative: false,
  },
  {
    id: 'carta-equity-forfeiture',
    title: 'Unvested Equity When Leaving',
    publisher: 'Carta',
    url: 'https://carta.com/learn/equity/leaving-company/',
    published: '2023',
    excerpt: 'When an employee leaves a company, only the vested portion of an option grant is retained; unvested options are forfeited.',
    whyItMatters: 'Ownership upside depends on tenure as well as company performance and should not be treated as immediate value.',
    tags: ['startup', 'equity', 'vesting', 'leaving', 'ownership', 'tenure'],
    quantitative: false,
  },
  {
    id: 'carta-equity-exercise-risk',
    title: 'Risk of Exercising Private Stock Options',
    publisher: 'Carta',
    url: 'https://carta.com/learn/equity/stock-options/exercising/',
    published: '2024',
    excerpt: 'Exercising private-company options requires paying cash for shares that may never become liquid when no tender offer or IPO occurs.',
    whyItMatters: 'Option ownership can require additional capital while still producing no spendable return.',
    tags: ['startup', 'equity', 'exercise', 'cash', 'liquidity', 'risk'],
    quantitative: false,
  },
  {
    id: 'carta-equity-tax-events',
    title: 'Tax Events for Employee Equity',
    publisher: 'Carta',
    url: 'https://carta.com/uk/en/learn/equity/equity-taxes/',
    published: '2025',
    excerpt: 'Vesting, exercising options, and selling shares can each create different employee tax obligations.',
    whyItMatters: 'The usable value of startup equity depends on tax treatment as well as the grant’s apparent value.',
    tags: ['startup', 'equity', 'tax', 'exercise', 'vesting', 'compensation'],
    quantitative: false,
  },
  {
    id: 'carta-equity-amt',
    title: 'Alternative Minimum Tax and Options',
    publisher: 'Carta',
    url: 'https://carta.com/learn/equity/stock-options/exercising/',
    published: '2024',
    excerpt: 'Exercising incentive stock options may create alternative minimum tax exposure based on the spread between strike price and fair market value.',
    whyItMatters: 'An option exercise can create a tax cost before the underlying private shares become liquid.',
    tags: ['startup', 'equity', 'AMT', 'tax', 'exercise', 'cash'],
    quantitative: false,
  },
  {
    id: 'carta-equity-strike-price',
    title: 'How Stock Options Become Shares',
    publisher: 'Carta',
    url: 'https://carta.com/learn/equity/',
    published: '2025',
    excerpt: 'A stock option gives an employee the right to buy shares at a defined strike price after the relevant options vest.',
    whyItMatters: 'Options are not free shares; realizing ownership may require both continued employment and an exercise payment.',
    tags: ['startup', 'equity', 'options', 'strike price', 'vesting', 'ownership'],
    quantitative: false,
  },
  {
    id: 'education-grants-versus-loans',
    title: 'Comparing Types of Student Aid',
    publisher: 'U.S. Department of Education, Federal Student Aid',
    url: 'https://studentaid.gov/articles/evaluating-financial-aid-offers/',
    published: '2026',
    excerpt: 'Federal Student Aid recommends distinguishing grants and scholarships from earned work-study funds and borrowed student loans.',
    whyItMatters: 'A program should be called funded only after separating nonrepayable support from work obligations and debt.',
    tags: ['graduate', 'funding', 'grants', 'loans', 'work study', 'cost'],
    quantitative: false,
  },
  {
    id: 'education-unsubsidized-interest',
    title: 'Unsubsidized Student Loan Interest',
    publisher: 'U.S. Department of Education, Federal Student Aid',
    url: 'https://studentaid.gov/articles/evaluating-financial-aid-offers/',
    published: '2026',
    excerpt: 'Interest on an unsubsidized federal student loan begins accruing without the government paying that interest during enrollment.',
    whyItMatters: 'Debt-funded study can grow in cost while the student delays full-time earnings.',
    tags: ['graduate', 'loans', 'interest', 'debt', 'opportunity cost', 'financial floor'],
    quantitative: false,
  },
  {
    id: 'education-plus-gap',
    title: 'Graduate PLUS Loans and Funding Gaps',
    publisher: 'U.S. Department of Education, Federal Student Aid',
    url: 'https://studentaid.gov/articles/evaluating-financial-aid-offers/',
    published: '2026',
    excerpt: 'Graduate and professional students may use Direct PLUS loans for education expenses not covered by other financial aid.',
    whyItMatters: 'An aid package that leaves a gap may transfer program risk into additional borrowing.',
    tags: ['graduate', 'PLUS loans', 'funding gap', 'debt', 'cost'],
    quantitative: false,
  },
  {
    id: 'education-work-study-earned',
    title: 'How Work-Study Funds Are Received',
    publisher: 'U.S. Department of Education, Federal Student Aid',
    url: 'https://studentaid.gov/articles/8-things-federal-work-study/',
    published: '2026',
    excerpt: 'Work-study funds are paid through a regular paycheck for work performed rather than provided upfront as guaranteed tuition support.',
    whyItMatters: 'Work-study consumes time and should not be modeled like an unconditional fellowship or grant.',
    tags: ['graduate', 'work study', 'employment', 'time', 'funding', 'income'],
    quantitative: false,
  },
  {
    id: 'education-work-study-renewal',
    title: 'Work-Study Availability',
    publisher: 'U.S. Department of Education, Federal Student Aid',
    url: 'https://studentaid.gov/articles/8-things-federal-work-study/',
    published: '2026',
    excerpt: 'Federal Work-Study funding and jobs are limited and are not guaranteed each year.',
    whyItMatters: 'A multi-year financial plan should not assume work-study income will automatically continue.',
    tags: ['graduate', 'work study', 'renewal', 'uncertainty', 'funding'],
    quantitative: false,
  },
  {
    id: 'bls-research-scientist-education',
    title: 'Computer Research Scientist Education',
    publisher: 'U.S. Bureau of Labor Statistics',
    url: 'https://www.bls.gov/ooh/computer-and-information-technology/computer-and-information-research-scientists.htm',
    published: '2025',
    excerpt: 'Computer and information research scientists typically need at least a master’s degree in computer science or a related field.',
    whyItMatters: 'Graduate study can be a direct credential path for research-oriented computing roles.',
    tags: ['research', 'masters', 'computer science', 'AI', 'career', 'credential'],
    quantitative: false,
  },
  {
    id: 'bls-research-scientist-work',
    title: 'Computer Research Scientist Work',
    publisher: 'U.S. Bureau of Labor Statistics',
    url: 'https://www.bls.gov/ooh/computer-and-information-technology/computer-and-information-research-scientists.htm#tab-2',
    published: '2025',
    excerpt: 'Computer and information research scientists design innovative uses for computing technology and solve complex computing problems.',
    whyItMatters: 'Research training aligns directly with a goal centered on developing new computing and AI methods.',
    tags: ['research', 'innovation', 'AI growth', 'technical depth', 'career'],
    quantitative: false,
  },
  {
    id: 'nsf-funding-forms',
    title: 'Forms of Graduate Research Support',
    publisher: 'U.S. National Science Foundation',
    url: 'https://www.nsf.gov/funding/graduate-students',
    published: '2026',
    excerpt: 'NSF graduate support can take several forms, including fellowships, research-project funding, traineeships, stipends, and education allowances.',
    whyItMatters: 'Funding labels must be translated into specific amounts, duration, duties, and renewal conditions.',
    tags: ['graduate', 'research', 'fellowship', 'traineeship', 'stipend', 'funding'],
    quantitative: false,
  },
  {
    id: 'nsf-funding-projects',
    title: 'Graduate Support Through Research Projects',
    publisher: 'U.S. National Science Foundation',
    url: 'https://www.nsf.gov/funding/graduate-students',
    published: '2026',
    excerpt: 'Graduate students may receive support through faculty-led NSF research awards as part of a project budget.',
    whyItMatters: 'Project-backed funding may connect financial support to concrete research experience, but depends on the award and advisor.',
    tags: ['graduate', 'research', 'project', 'advisor', 'funding', 'lab'],
    quantitative: false,
  },
]

export const BUILTIN_RETRIEVAL_QUERIES = [
  'software engineering career stability salary outlook mentorship',
  'startup survival uncertainty early stage company risk',
  'funded research masters AI graduate support lab access stipend',
  'graduate school funding loans work study opportunity cost',
  'private startup equity liquidity risk options not cash',
  'research masters funded stipend tuition fellowship changes cost',
]
